import Link from 'next/link'
import type { ReactNode } from 'react'

import { buildFairlendMetadata } from '@/utilities/seo'

type PolicyBlock = {
  level?: 0 | 1
  text: string
  type: 'heading' | 'list' | 'paragraph' | 'title'
}

const policyUrl = '/en/brokerage/privacy-policy'

export const dynamic = 'force-static'

export const metadata = buildFairlendMetadata({
  description:
    'Read the Fairlend Management Inc. privacy policy for mortgage administration, brokerage activities, website privacy, consent, disclosure, retention, and contact rights.',
  path: policyUrl,
  title: 'Privacy Policy | Fairlend Management Inc.',
})

const inlineLinks = [
  { href: 'https://www.fairlend.ca', text: 'www.fairlend.ca' },
  { href: 'https://www.priv.gc.ca', text: 'www.priv.gc.ca' },
  { href: 'http://youradchoices.ca/', text: 'http://youradchoices.ca/' },
  { href: 'https://tools.google.com/dlpage/gaoptout', text: 'Google Analytics opt-out page' },
  { href: 'https://adssettings.google.com/', text: 'Google’s Ads Preferences Manager' },
  { href: 'https://youradchoices.ca/choices/', text: 'DAAC opt-out page' },
  { href: 'tel:+16474391232', text: '647-439-1232' },
  { href: 'tel:+18002821376', text: '1-800-282-1376' },
  { href: 'mailto:elie@fairlend.ca', text: 'elie@fairlend.ca' },
]

const policyBlocks = [
  {
    type: 'title',
    text: 'Privacy Policy',
  },
  {
    type: 'paragraph',
    text: 'Fairlend Management Inc., operating as FairLend Mortgage ("FairLend"), is licensed by FSRA as both a mortgage brokerage and mortgage administrator. FairLend helps customers find the most suitable mortgage product for their needs and may, with the customer\'s consent, refer customers to duly-licensed insurance brokerages for related insurance products.',
  },
  {
    type: 'paragraph',
    text: 'At FairLend, we know that the protection of your privacy is important to you. For this reason, we have taken steps to ensure that any personal information that you provide to FairLend is protected by a range of robust business procedures and rigorous security safeguards to ensure that your information is kept confidential and used only for the purposes detailed in this privacy policy. This privacy policy is intended to establish responsible and transparent practices for the management of personal information and to satisfy the requirements of rules established by the *Personal Information Protection and Electronic Documents Act* (PIPEDA), and similar provincial laws from Quebec, Alberta and B.C.',
  },
  {
    type: 'heading',
    text: 'Application and Scope',
  },
  {
    type: 'paragraph',
    text: 'Fairlend Management Inc. carries on business under the authorized name "FairLend Mortgage" and is licensed by FSRA as both a mortgage brokerage and a mortgage administrator. All references in this privacy policy to "FairLend" include Fairlend Management Inc. operating as FairLend Mortgage. As a mortgage brokerage, FairLend assists prospective borrowers in obtaining mortgages from lenders. As a mortgage administrator, FairLend services mortgages on behalf of lenders, including processing payments and coordinating with lenders, borrowers, and other parties throughout the life of the mortgage. This privacy policy applies to personal information FairLend collects, uses, or discloses in connection with both of these licensed activities. The persons whose personal information is covered by this policy include mortgage applicants, borrowers, co-borrowers, guarantors, lenders, suppliers and service providers, prospective customers, website visitors, and any other individuals whose personal information FairLend handles in the course of its business.',
  },
  {
    type: 'paragraph',
    text: 'This privacy policy generally applies to any personal information (as defined below in the section entitled Definition of Personal Information) collected or generated by FairLend, its brokers or anyone acting as an agent on our behalf ("Authorized Agent"), from or about its customers and other individuals with whom it deals, which may include potential customers as well as any other additional person named on an account, in any form. At any time that you do business with FairLend, participate in a contest or promotion run by FairLend, a FairLend broker or with an Authorized Agent, or interact with us in any manner, you are protected by the rights and safeguards contained in this privacy policy and you explicitly agree to its terms.',
  },
  {
    type: 'paragraph',
    text: 'This privacy policy also governs personal information collected about FairLend\'s website users and explains how we use and disclose personal information that we collect from users who visit our website and otherwise interact with us through www.fairlend.ca ("website"). It also explains how we use cookies and similar technologies.',
  },
  {
    type: 'heading',
    text: 'Definition of Personal Information',
  },
  {
    type: 'paragraph',
    text: 'When used in this privacy policy, personal information means "any information about an identifiable individual". This may include, for example, your name, contact information, email address, information relating to your account with us, including your identity and the mortgage you take out, as well as your credit and banking information, billing records and any complaints documented in a file. It may also include other types of more technical information when you interact with us through our website, when this information can identify you as an individual. Personal information that is aggregated and cannot be associated with an identifiable individual is not considered to be personal information.',
  },
  {
    type: 'heading',
    text: 'Collection and Use of Personal Information',
  },
  {
    type: 'paragraph',
    text: 'We collect most of our information about you directly from you, with your consent.',
  },
  {
    type: 'paragraph',
    text: "We usually collect your name, address, phone number(s), email address, occupation, employer's name, birth date, annual income, net worth, assets, liabilities, credit history, investment objectives, banking information, as well as other account and payment information, including information pertaining to your use of our products and services when you register to FairLend services. We may also collect other information such as your social insurance number, driver's license or passport number, when required and/or authorized by law, for instance to fulfill regulatory and other governmental obligations and to distinguish you from other clients with similar names.",
  },
  {
    type: 'paragraph',
    text: 'FairLend is a reporting entity under the *Proceeds of Crime (Money Laundering) and Terrorist Financing Act* and may collect, use, and retain personal information — including identification documents, occupation, source of funds, and beneficial ownership information — as required to comply with that Act.',
  },
  {
    type: 'paragraph',
    text: 'We may also obtain information about you from third parties, with your consent. For example, for credit evaluation purposes, we may need to determine your creditworthiness through contact with an independent credit reporting agency or another source, which may include account information. FairLend uses this information to help determine the product or service that is suitable to your mortgage needs. We may also collect personal information from other third parties, such as your spouse, if you are applying for certain products and services, and information about beneficial owners, intermediaries and other parties.',
  },
  {
    type: 'paragraph',
    text: "We may also collect and use publicly available information from government open data sources, including the City of Toronto's Open Data portal (for example, building permit and development application datasets), for marketing purposes, such as identifying properties and property owners who may benefit from our construction financing and mortgage products, conducting market research, and informing our outreach activities. We collect and use such information in accordance with applicable privacy laws governing the use of publicly available information.",
  },
  {
    type: 'paragraph',
    text: 'FairLend generally collects personal information from or about its customers and other individuals with whom it deals for the following purposes:',
  },
  {
    type: 'list',
    text: "to confirm and/or authenticate customers' identity, to determine customers' eligibility for FairLend's products and services and as necessary, to establish or verify the credit of customers that use, or intend to use, one or more of the products or services offered by FairLend;",
    level: 0,
  },
  {
    type: 'list',
    text: "to process customers' applications or requests, to provide the products or services that it offers, or receive the products or services that it requests, and ensure that all related transactions are supported and implemented;",
    level: 0,
  },
  {
    type: 'list',
    text: 'to monitor, review and improve customer service, manage its business, establish, develop and preserve its business relationship respectively with its customers and other individuals with whom it deals;',
    level: 0,
  },
  {
    type: 'list',
    text: "to create, establish and administer customers' mortgage financing or accounts and to respond to customer or supplier inquiries;",
    level: 0,
  },
  {
    type: 'list',
    text: 'for internal training and quality assurance purposes, to meet legal and regulatory requirements and to allow FairLend to meet contractual requirements relating to the products and services provided to customers;',
    level: 0,
  },
  {
    type: 'list',
    text: 'to understand and assess the interests, wants and changing needs of customers with a view to improving its products and services and developing new ones, and to provide personalized products and services as well as product recommendations to customers;',
    level: 0,
  },
  {
    type: 'list',
    text: "subject to our customers' Right to Withdraw Consent, to conduct surveys on the quality of our products, services or customer service or to provide our customers with offers for additional products and services that we feel may be of interest to our customers or that we believe meet our customers' changing needs;",
    level: 0,
  },
  {
    type: 'list',
    text: 'to service and administer mortgages on behalf of lenders, including processing payments from borrowers, remitting funds to lenders, maintaining account records, preparing periodic statements for borrowers and lenders, and communicating with borrowers, lenders, co-borrowers, and guarantors regarding the status of mortgages;',
    level: 0,
  },
  {
    type: 'list',
    text: 'to collect, use, and retain personal information from lenders (including contact information, banking information for payment routing, signing authority documentation, and tax identification numbers) for the purposes of administering mortgages, remitting funds, and preparing tax information returns required under the *Income Tax Act* (Canada), including T5 and NR4 information returns;',
    level: 0,
  },
  {
    type: 'list',
    text: 'to coordinate with legal counsel, real estate professionals, court officers, property managers, and other parties as required in connection with the renewal, discharge, or enforcement of mortgages, including in default scenarios such as power-of-sale proceedings.',
    level: 0,
  },
  {
    type: 'paragraph',
    text: 'If you have applied for employment with FairLend, the personal information submitted with your job application will be used for recruitment and other customary human resources purposes. For example, we may send you information about new job opportunities within FairLend as well as other career development resources.',
  },
  {
    type: 'paragraph',
    text: 'Unless required or authorized by law, FairLend will not collect or use personal information for any other or new purpose without obtaining further consent. For details on the type of information that we collect via our website and on how we use and share this information, please refer to the Website section of this privacy policy.',
  },
  {
    type: 'paragraph',
    text: 'From time to time, FairLend may offer simulators on its website. Where offered, these simulators are designed to collect information about you or your financial situation. The details are then used to establish your type of profile with a view to helping you choose the most suitable product for your particular needs.',
  },
  {
    type: 'heading',
    text: 'Your Consent',
  },
  {
    type: 'paragraph',
    text: "FairLend obtains consent from the individuals concerned for the collection, use or disclosure of personal information through various means. The most common method we use to obtain a customer's consent is by way of the customer's consent as confirmed by consent forms. Where practicable, we may also obtain a customer's consent through electronic communications or other written documentation.",
  },
  {
    type: 'paragraph',
    text: 'In general, by requesting FairLend products and services and/or submitting information to us in connection with using FairLend products and services, you are providing your consent to the collection, use and disclosure of personal information as set out in this privacy policy and in the FairLend contractual documents. Moreover, by visiting, interacting with and/or using our websites, you agree to benefit from, be bound by, the terms and conditions of this privacy policy.',
  },
  {
    type: 'paragraph',
    text: 'In certain circumstances, personal information may be collected, used or disclosed without consent. These exceptional circumstances may include:',
  },
  {
    type: 'list',
    text: 'when information is being collected, used or shared for the detection, prevention of or remediation to, the breach of an agreement, fraud or other illegal activity, and the collection of consent might defeat the purpose of collecting the information;',
    level: 0,
  },
  {
    type: 'list',
    text: 'to collect a debt; and',
    level: 0,
  },
  {
    type: 'list',
    text: 'to comply with a subpoena, warrant or other court order, or as may be otherwise required or authorized by law or by any regulatory bodies having jurisdiction.',
    level: 0,
  },
  {
    type: 'paragraph',
    text: 'For more information on how FairLend may share your personal information, please refer to section Sharing of Personal Information of this privacy policy.',
  },
  {
    type: 'heading',
    text: 'Right to Withdraw Consent',
  },
  {
    type: 'paragraph',
    text: 'Consent may be withdrawn at any time, subject to legal or contractual restrictions and reasonable notice. Depending on the circumstances, however, any withdrawal or amendment to your consent may prevent us from providing you, or continuing to provide you, with FairLend products and services or information that may be of value to you. You may also withdraw your consent as follows:',
  },
  {
    type: 'list',
    text: '**Mail marketing, telephone marketing and quality control communications.** You may decide that you prefer FairLend or Authorized Agents not to use your personal information to promote new and/or additional products and/or services which may be of interest to you and refuse that we contact you by mail or telephone for marketing purposes or by email or telephone for quality control purposes. If this is the case, you may advise us by contacting customer service or contacting us using the information detailed in the How to Contact Us section below.',
    level: 0,
  },
  {
    type: 'list',
    text: '**Commercial Electronic Communications.** You can always limit the communications that FairLend or Authorized Agents send to you. To opt-out of commercial emails, simply click the link labeled "unsubscribe" or "opt-out" at the bottom of any commercial electronic communication we send you. Please note that even if you opt-out of promotional communications, we may still need to contact you with information about your account.',
    level: 0,
  },
  {
    type: 'paragraph',
    text: 'For information on how you can limit the type of information that we collect, use or share about you when you visit and/or use our website, please refer to the Website section of this privacy policy.',
  },
  {
    type: 'heading',
    text: 'Sharing of Personal Information',
  },
  {
    type: 'paragraph',
    text: 'Your information may be made available by FairLend to Authorized Agents or service providers to fulfill the purposes for which it has been collected or as set forth in this privacy policy. FairLend will not sell, rent or trade your personal information to any third party. However, we may share your personal information when authorized by law or as follows:',
  },
  {
    type: 'list',
    text: '**Financial institutions and credit.** We may share your personal information with financial institutions in connection with the administration and management of the products and services that you have requested, as well as convey your credit file to credit reporting and assessment agencies, insurers or other lenders, as applicable.',
    level: 0,
  },
  {
    type: 'list',
    text: '**Lenders.** Where FairLend acts as administrator of a mortgage, we will share borrower personal information (including payment status, account balances, default information where applicable, and other servicing information) with the lender or lenders who hold the mortgage, as required to administer the mortgage in accordance with the applicable administration agreement and applicable law.',
    level: 0,
  },
  {
    type: 'list',
    text: '**Tax authorities.** We may share personal information, including taxpayer identification numbers, with the Canada Revenue Agency and other applicable tax authorities for the purposes of preparing and filing tax information returns, including T5 and NR4 information returns required in connection with interest paid to lenders.',
    level: 0,
  },
  {
    type: 'list',
    text: '**Payment processors.** We may share banking and payment information with regulated payment processors and financial institutions for the purposes of processing mortgage payments, remitting funds to lenders, and managing related transactions.',
    level: 0,
  },
  {
    type: 'list',
    text: '**Counsel and professionals in enforcement scenarios.** In the event of a mortgage default, renewal, discharge, or other circumstance requiring professional involvement, we may share personal information with legal counsel, court officers, real estate professionals, property managers, and other professionals to the extent necessary to coordinate the relevant action in accordance with applicable law.',
    level: 0,
  },
  {
    type: 'list',
    text: '**Service providers and Authorized Agents.** We do not directly provide all of our products and services. For example, in some cases we rely on assessment agencies, real estate appraisers, financial institutions, insurance agents or brokers, public registers, employers, credit reporting and collection agencies, professionals, our subsidiaries and affiliated companies, as well as other third parties to provide you with the products and services. We may therefore disclose information about you to such providers or agents in order for us to provide you with the requested products and services. We provide them with information which is necessary in order for them to provide the services required. They are prohibited from using the information for purposes other than to facilitate and carry out the services they have been engaged to provide. These service providers and agents are not permitted to disclose this information to others.',
    level: 0,
  },
  {
    type: 'list',
    text: '**Affiliated entities.** We may share your personal information with our affiliated entities for legal and regulatory purposes, to perform analytics, to provide you with a suitable range of products and services, and to better manage your relationship with you.',
    level: 0,
  },
  {
    type: 'list',
    text: '**As permitted or required by law.** FairLend may disclose information when compelled in response to a law, regulation, court order, subpoena, valid demand, search warrant, government investigation or other legally valid request or enquiry. We may also disclose information to our accountants, auditors, agents and lawyers in connection with the enforcement or protection of our legal rights. We also reserve the right to report to law enforcement agencies any activities that we, in good faith, believe to be unlawful or to law enforcement and emergency services providers, in an emergency or where required or permitted by law. We may release certain personal information when we have reasonable grounds to believe that such release is reasonably necessary to protect the rights, property and safety of others and ourselves, in accordance with or as authorized by law.',
    level: 0,
  },
  {
    type: 'list',
    text: '**Business transaction.** We may disclose personal information to a third party in connection with a sale or transfer of business or assets, an amalgamation, re-organization or financing of parts of our business. However, in the event the transaction is completed, your personal information will remain protected by applicable privacy laws. In the event the transaction is not completed, we will require the other party not to use or disclose your personal information in any manner whatsoever and to completely delete such information.',
    level: 0,
  },
  {
    type: 'list',
    text: "**Other types of sharing.** We may also disclose our customers' personal information to an individual who, in the reasonable judgement of FairLend, is acting on behalf of the individual in question, such as through a power of attorney.",
    level: 0,
  },
  {
    type: 'paragraph',
    text: 'For information on how you can limit the type of information that we collect, use or share about you when you visit and/or use our website, please refer to the Website section of this privacy policy.',
  },
  {
    type: 'heading',
    text: 'Business Analytics',
  },
  {
    type: 'paragraph',
    text: "We may share aggregated customers and/or website users' information with our partners. This information does not allow identifying individual customers nor users, and is only used to provide our partners a better understanding of the general profile of customers of our products and/or services and users of our website, trends in the industry, or similar type of information. We do not link aggregate user data with personal information.",
  },
  {
    type: 'heading',
    text: 'Website Privacy',
  },
  {
    type: 'paragraph',
    text: 'FairLend generally collects and uses personal information from or about its website visitors and users as follows:',
  },
  {
    type: 'list',
    text: '**Information you provide.** In many cases, we collect personal information directly from you when you visit or use our website. For instance, we may collect the following type of information:',
    level: 0,
  },
  {
    type: 'list',
    text: '**Inquiries.** We may collect your name, contact information, e-mail address and any information you provide us when you make an inquiry or contact us through our website. We will only use this information to provide you with the information requested or to contact you in order to answer your questions and/or requests.',
    level: 1,
  },
  {
    type: 'list',
    text: '**Registration.** In order to receive electronic communications, you must first complete a registration form and provide your contact information (such as name and email address). If you wish to subscribe to our electronic communications, we will use your name and email address to send communications to you. We will always provide you a way to unsubscribe. For more information on how to unsubscribe, please refer to the section Right to Withdraw Consent of this privacy policy.',
    level: 1,
  },
  {
    type: 'list',
    text: '**Application forms.** We may collect your name, contact information, e-mail address and any other information provided to us when you complete one of our online forms for a mortgage request, request for other product or service or application, online pre-qualification, refinancing and/or renewal application forms available on our website. We will only use this information to process and answer your request or to manage our everyday business needs in connection with such request. If you file an application on our website, we require that you provide certain personal information, including your name, address, phone number, email, and current employment information. This information is necessary to process your application and to contact you. We do not require your social insurance number to accept an online application; however you may choose to provide that information via the online application to expedite the servicing of your application.',
    level: 1,
  },
  {
    type: 'list',
    text: '**Satisfaction survey.** When you visit our website, you may, from time to time, be invited to participate in a satisfaction survey. In such case and if you decide to participate in our survey, we may collect your postal code, email address and other information deemed important to complete such survey. We use this information to measure our overall service levels and as a resource to gather information regarding concerns our customers may have. You may be contacted if we feel the comments you express warrant further investigation. When we use a third party service provider to conduct these surveys or contests, that service provider is prohibited from using personal information for any secondary reasons. We will not share the personal information you provide through a survey with other third parties unless we give you prior notice and choice.',
    level: 1,
  },
  {
    type: 'list',
    text: "**Technical information.** When you visit our website, we may collect technical information, using electronic means such as cookies. This information may include information about your visit to our website, including the IP address of your computer and which browser you used to view our website, your operating system, resolution of screen, location, language settings in browsers, the site you came from, keywords searched (if arriving from a search engine), the number of page views, information you entered, advertisements you have seen, etc. This data is used to determine the user's approximate geographic location, to measure and improve the effectiveness of our website or enhance the experience for our customers. For instance, it may be used to ensure that the products advertised on our website are available in your area or that we are not showing you the same ads repeatedly. We treat this information as personal information when it is associated with your account or contact information. For instance, we may collect and use the following type of information when you visit and/or interact with us on our websites:",
    level: 0,
  },
  {
    type: 'list',
    text: '**First-party QR campaign attribution:** When you enter our website through a FairLend QR campaign link, we set a first-party cookie for up to 30 days containing a random scan identifier and campaign information. We use it to connect that scan with completed website intake forms, consultation bookings, or other form submissions and to measure campaign performance. With analytics consent, we also associate page paths and time-on-page events with that random identifier so we can understand navigation and abandonment. Form answers are not copied into the campaign journey log. Clearing the cookie prevents future activity on that browser from being linked to the scan.',
    level: 1,
  },
  {
    type: 'list',
    text: '**Google Analytics:** We may use Google Analytics, which allows us to see information on user website activities including, but not limited to, page views, source and time spent on our website. Where used, this information is depersonalized and is displayed as numbers, meaning that it cannot be tracked back to individuals. You may opt-out of our use of Google Analytics by visiting the Google Analytics opt-out page.',
    level: 1,
  },
  {
    type: 'list',
    text: '**PostHog:** With your analytics consent, we use PostHog to understand page visits, navigation paths, clicks, form-step progress, website performance, errors, and where visitors leave an intake journey. PostHog may use cookies or similar browser storage and may create a session replay of approved public website surfaces. We mask all form inputs and other elements that may display information you provide, exclude request and response bodies and sensitive headers, and do not send form answers, contact details, financial values, property values, uploaded document details, or FairLend database identifiers to PostHog. We do not initialize PostHog or begin a replay before analytics consent. You can withdraw analytics consent at any time through Cookie Settings; withdrawal stops future browser capture, resets the analytics identity, and prevents future PostHog CRM lifecycle updates for leads submitted from that browser.',
    level: 1,
  },
  {
    type: 'list',
    text: "**Google Ads:** We may use Google Ads, including Google Ads Remarketing, to advertise FairLend across the internet and to advertise on third party websites (including Google) to previous visitors to our websites. Google Ads Remarketing will display ads to you based on what parts of the FairLend website you have viewed by placing a cookie on your web browser. It could mean that we advertise to previous visitors who haven't completed a task on our site or this could be in the form of an advertisement on the Google search results page, or a site in the Google Display Network. This cookie does not in any way identify you or give access to your computer or mobile device. The cookie is only used to indicate to other websites that you have visited a particular page on our website, so that they may show you ads relating to that page. If you do not wish to participate in our Google Ads Remarketing, you can opt out by visiting Google's Ads Preferences Manager.",
    level: 1,
  },
  {
    type: 'list',
    text: "**LinkedIn Insight Tag and Analytics:** We may use the LinkedIn Insight Tag and LinkedIn analytics tools to measure the performance of our LinkedIn advertising campaigns, understand the professional demographics of our website visitors in aggregate, and serve relevant advertising to website visitors on LinkedIn. The Insight Tag places a cookie on your browser and collects information such as URL, referrer, IP address, device and browser characteristics, and timestamp. You can manage your LinkedIn advertising preferences and opt out through your LinkedIn account settings or LinkedIn's cookie policy page.",
    level: 1,
  },
  {
    type: 'list',
    text: '**Meta Pixel and Analytics:** We may use the Meta Pixel and related Meta (Facebook and Instagram) analytics and advertising tools to measure the effectiveness of our advertising on Meta platforms, understand actions visitors take on our website, and deliver relevant advertising to website visitors on Facebook and Instagram. The Meta Pixel places cookies or uses similar technologies to collect information about your interactions with our website. You can manage your Meta advertising preferences through your Facebook or Instagram ad settings, and can opt out of interest-based advertising as described in the Third Party Advertising section below.',
    level: 1,
  },
  {
    type: 'list',
    text: '**Third Party Advertising:** We may use third-party advertising companies to collect data and/or serve ads when you visit our website. These companies may use information about your visits to our website and other websites in order to provide advertisements about goods and services of interest to you, at all times, in compliance with applicable privacy laws. These companies may also use other types of technologies to recognize your computer or device and/or to collect and record information about your web surfing activity including your activities on or off this website. Please keep in mind that your web browser may not permit you to block the use of these non-cookie technologies, and those browser settings that block cookies may have no effect on such techniques. You can also generally opt-out of receiving personalized ads from third party advertisers and ad networks who are members of the Digital Advertising Alliance of Canada. Please visit the DAAC opt-out page for more information, including if you would like more information about this practice and to know your choices about not having this information used by these companies at: http://youradchoices.ca/.',
    level: 1,
  },
  {
    type: 'list',
    text: '**Your choice with cookies.** You can block the use of cookies by activating the settings in your browser, except for some of the cookies used for third-party advertising, as detailed above under the section Third Party Advertising. The "Help" feature on most browsers will tell you how to prevent your browser from accepting new cookies, how to have the browser notify you when you receive a new cookie, or how to disable cookies altogether. If you choose to withhold consent, or subsequently block cookies, you may not be able to access all or part of the content of our website. Additionally, you can disable or delete similar data used by browser add-ons, by changing the add-on\'s settings or visiting the website of its manufacturer.',
    level: 0,
  },
  {
    type: 'list',
    text: '**Privacy policies of third parties.** This privacy policy only addresses the use and disclosure of information by FairLend. Other websites that may be accessible through FairLend websites have their own privacy policies and data collection, use and disclosure practices. We encourage you to familiarize yourself with the privacy statements provided by all third parties prior to providing them with information or taking advantage of an offer or promotion.',
    level: 0,
  },
  {
    type: 'heading',
    text: 'Mobile App Data Collection',
  },
  {
    type: 'paragraph',
    text: 'In the event that you download and/or use any of our applications, we may require and collect, directly from you, information necessary to authenticate you. We may also record your IP geolocation, allowing us to block the access when the user is outside of Canada. When you register on certain apps, you may be required to agree that we may send you notifications regarding your property evaluation, credit score, or general information by electronic messaging on a periodic basis. If you no longer want to receive any notifications, you can unsubscribe at any time.',
  },
  {
    type: 'heading',
    text: 'Quality and Access Rights',
  },
  {
    type: 'paragraph',
    text: "FairLend strives to ensure that customers' personal information is as accurate, complete, and up-to-date as is necessary for the purposes for which it is used. FairLend provides customer access to their personal information. Customers may correct or amend any inaccuracies in their personal information by contacting us using the contact information detailed in the section How to Contact Us of this privacy policy. FairLend has the right to refuse a request for access to personal information if the information is protected by legal privilege, granting access would reveal confidential commercial information, the information was collected for purposes related to the detection and prevention of fraud, the information was generated in the course of a formal dispute resolution process, the information would likely reveal personal information about another individual, the request is vexatious or frivolous or any other reason, as authorized under applicable laws.",
  },
  {
    type: 'heading',
    text: 'Personal Information Outside of Canada',
  },
  {
    type: 'paragraph',
    text: 'In some cases, personal information that we manage may be transferred, processed and stored outside Canada, and therefore may be available to government authorities under lawful orders and laws applicable there.',
  },
  {
    type: 'heading',
    text: 'Security of Personal Information',
  },
  {
    type: 'paragraph',
    text: 'We will use reasonable security measures to protect your personal information against unauthorized access. FairLend has implemented security measures that contain administrative, technical and physical controls that are designed to safeguard your personal information. No method of transmission over the internet, or method of electronic storage, is 100% secure, however.',
  },
  {
    type: 'paragraph',
    text: 'In the event of a breach of security safeguards involving personal information that creates a real risk of significant harm, FairLend will notify affected individuals and the Office of the Privacy Commissioner of Canada in accordance with PIPEDA, and will maintain a record of the breach.',
  },
  {
    type: 'heading',
    text: 'Retention',
  },
  {
    type: 'paragraph',
    text: 'Personal information will be retained only as long as necessary for the fulfilment of the purposes for which it was collected and for which consent was received or to satisfy legal requirements.',
  },
  {
    type: 'heading',
    text: 'How to Contact Us',
  },
  {
    type: 'paragraph',
    text: 'If you have questions, concerns or complaints regarding this privacy policy or the personal information that FairLend has about you, or to withdraw consent (when applicable) please contact:',
  },
  {
    type: 'paragraph',
    text: '**Elie Soberano**\nPrincipal Broker – Privacy Officer\n#M08001537\nFairlend Management Inc.\nUnit #2 - 890 Sheppard Avenue\nNorth York, Ontario M3H 6B9\nBy phone: 647-439-1232\nBy e-mail: elie@fairlend.ca',
  },
  {
    type: 'paragraph',
    text: 'If you are not satisfied with our response to a privacy inquiry or complaint, you may contact the Office of the Privacy Commissioner of Canada at 1-800-282-1376 or www.priv.gc.ca.',
  },
  {
    type: 'heading',
    text: 'Change of Privacy Policy',
  },
  {
    type: 'paragraph',
    text: 'FairLend will review and update its policies and procedures as required to keep current with rules and regulations, new technologies, standards and customer concerns. Our privacy policy may therefore change from time to time. We will post any privacy policy changes on our website and, if the changes are material, we will provide a more prominent notice. This privacy policy was last updated on July 8, 2026.',
  },
  {
    type: 'paragraph',
    text: '**Fairlend Management Inc. o/a FairLend Mortgage**\nFSRA Mortgage Brokerage Licence #13827\nFSRA Mortgage Administrator Licence #13828',
  },
] satisfies PolicyBlock[]

const titleBlock = policyBlocks.find((block) => block.type === 'title')
const contentBlocks = policyBlocks.filter((block) => block.type !== 'title')

function renderLinkedText(text: string, keyPrefix: string) {
  const nodes: ReactNode[] = []
  let cursor = 0

  while (cursor < text.length) {
    const nextLink = inlineLinks
      .map((link) => ({ ...link, index: text.indexOf(link.text, cursor) }))
      .filter((link) => link.index !== -1)
      .sort((a, b) => a.index - b.index || b.text.length - a.text.length)[0]

    if (!nextLink) {
      nodes.push(text.slice(cursor))
      break
    }

    if (nextLink.index > cursor) {
      nodes.push(text.slice(cursor, nextLink.index))
    }

    nodes.push(
      <Link
        className="font-semibold text-[#2f4f00] underline decoration-[#96ec18] decoration-2 underline-offset-4 transition-colors hover:text-[#0f1f00]"
        href={nextLink.href}
        key={`${keyPrefix}-${nextLink.text}-${nextLink.index}`}
      >
        {nextLink.text}
      </Link>,
    )
    cursor = nextLink.index + nextLink.text.length
  }

  return nodes
}

function renderInlineText(text: string) {
  const nodes: ReactNode[] = []
  let cursor = 0

  while (cursor < text.length) {
    const boldStart = text.indexOf('**', cursor)
    const italicStart = text.indexOf('*', cursor)
    const isBold = boldStart !== -1 && boldStart === italicStart
    const markerStart = isBold ? boldStart : italicStart

    if (markerStart === -1) {
      nodes.push(...renderLinkedText(text.slice(cursor), `${cursor}-plain`))
      break
    }

    if (markerStart > cursor) {
      nodes.push(...renderLinkedText(text.slice(cursor, markerStart), `${cursor}-plain`))
    }

    const marker = isBold ? '**' : '*'
    const markerEnd = text.indexOf(marker, markerStart + marker.length)

    if (markerEnd === -1) {
      nodes.push(...renderLinkedText(text.slice(markerStart), `${markerStart}-plain`))
      break
    }

    const content = text.slice(markerStart + marker.length, markerEnd)
    nodes.push(
      isBold ? (
        <strong className="font-bold text-[#191915]" key={`${markerStart}-bold`}>
          {renderInlineText(content)}
        </strong>
      ) : (
        <em key={`${markerStart}-italic`}>{renderInlineText(content)}</em>
      ),
    )
    cursor = markerEnd + marker.length
  }

  return nodes
}

function renderText(text: string) {
  return text.split('\n').map((line, index) => (
    <span key={`${line}-${index}`}>
      {index > 0 ? <br /> : null}
      {renderInlineText(line)}
    </span>
  ))
}

function renderPolicyBlocks(blocks: PolicyBlock[]) {
  const rendered: ReactNode[] = []
  let pendingList: PolicyBlock[] = []

  function flushList() {
    if (pendingList.length === 0) return

    const items = pendingList
    pendingList = []
    rendered.push(
      <ul
        className="my-6 space-y-3 border-l border-[#96ec18]/70 pl-5"
        key={`list-${rendered.length}`}
      >
        {items.map((item, index) => (
          <li
            className={item.level ? 'ml-5 pl-2 text-base leading-7' : 'pl-2 text-base leading-7'}
            key={`${item.text}-${index}`}
          >
            <span className="mr-3 inline-block size-1.5 translate-y-[-2px] rounded-full bg-[#96ec18]" />
            <span>{renderText(item.text)}</span>
          </li>
        ))}
      </ul>,
    )
  }

  blocks.forEach((block, index) => {
    if (block.type === 'list') {
      pendingList.push(block)
      return
    }

    flushList()

    if (block.type === 'heading') {
      rendered.push(
        <h2
          className="mt-12 border-t border-black/10 pt-8 font-serif text-3xl leading-tight font-bold text-[#090909] first:mt-0 first:border-t-0 first:pt-0 sm:text-4xl"
          key={`${block.text}-${index}`}
        >
          {block.text}
        </h2>,
      )
      return
    }

    rendered.push(
      <p className="my-5 text-base leading-8 text-[#34342f]" key={`${block.text}-${index}`}>
        {renderText(block.text)}
      </p>,
    )
  })

  flushList()
  return rendered
}

export default function FairlendPrivacyPolicyPage() {
  return (
    <main className="min-h-svh bg-[#f8f7f5] text-[#090909]">
      <section className="border-b border-black/10 bg-[linear-gradient(135deg,#ffffff_0%,#f8f7f5_54%,rgb(150_236_24/13%)_100%)] px-5 pt-24 pb-14 sm:px-8 lg:px-12 lg:pt-32 lg:pb-20">
        <div className="mx-auto grid w-full max-w-6xl gap-8 lg:grid-cols-[minmax(0,0.72fr)_minmax(280px,0.28fr)] lg:items-end">
          <div>
            <p className="mb-5 text-xs font-extrabold tracking-[0.28em] text-[#395d00] uppercase">
              Legal / Brokerage
            </p>
            <h1 className="max-w-4xl font-serif text-[clamp(3.3rem,9vw,7.5rem)] leading-[0.88] font-bold tracking-normal text-[#090909]">
              {titleBlock?.text ?? 'Privacy Policy'}
            </h1>
            <p className="mt-7 max-w-3xl text-base leading-8 font-medium text-[#46463f] sm:text-lg">
              Fairlend Management Inc. privacy policy for mortgage brokerage and administration
              activities, website use, consent, disclosure, retention, and privacy contact rights.
            </p>
          </div>
          <aside className="border border-black/10 bg-white/78 p-5 shadow-[0_18px_48px_rgb(8_9_10/7%)]">
            <p className="text-xs font-extrabold tracking-[0.22em] text-[#395d00] uppercase">
              Current policy
            </p>
            <dl className="mt-5 space-y-4 text-sm">
              <div>
                <dt className="font-bold text-[#090909]">Last updated</dt>
                <dd className="mt-1 text-[#5a5a52]">July 14, 2026</dd>
              </div>
              <div>
                <dt className="font-bold text-[#090909]">Administrator licence</dt>
                <dd className="mt-1 text-[#5a5a52]">FSRA #13828</dd>
              </div>
              <div>
                <dt className="font-bold text-[#090909]">Brokerage licence</dt>
                <dd className="mt-1 text-[#5a5a52]">FSRA #13827</dd>
              </div>
            </dl>
          </aside>
        </div>
      </section>

      <article className="mx-auto w-full max-w-4xl px-5 py-14 sm:px-8 lg:py-20">
        {renderPolicyBlocks(contentBlocks)}
      </article>
    </main>
  )
}
