import { defineObject, FieldType, RelationType, STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS } from 'twenty-sdk/define';

import {
  CONSULTATION_FIELD_IDS,
  CONSULTATION_OBJECT_ID,
  MORTGAGE_LEAD_FIELD_IDS,
  MORTGAGE_LEAD_OBJECT_ID,
  STANDARD_OBJECT_RELATION_FIELD_IDS,
} from 'src/constants/data-model';

export default defineObject({
  universalIdentifier: CONSULTATION_OBJECT_ID,
  nameSingular: 'fairlendConsultation',
  namePlural: 'fairlendConsultations',
  labelSingular: 'Consultation',
  labelPlural: 'Consultations',
  description: 'Consultation bookings created by FairLend intake flows and calendar integrations.',
  icon: 'IconCalendarEvent',
  isSearchable: true,
  isUICreatable: true,
  isUIEditable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: CONSULTATION_FIELD_IDS.name,
  fields: [
    {
      universalIdentifier: CONSULTATION_FIELD_IDS.name,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Consultation',
      defaultValue: 'New consultation',
      isNullable: false,
    },
    {
      universalIdentifier: CONSULTATION_FIELD_IDS.bookingId,
      type: FieldType.TEXT,
      name: 'bookingId',
      label: 'Booking ID',
      description: 'Stable booking UUID from FairLend.',
      isNullable: true,
      isUnique: true,
      isUIEditable: false,
    },
    {
      universalIdentifier: CONSULTATION_FIELD_IDS.status,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      defaultValue: 'SYNCING',
      isNullable: false,
      options: [
        { value: 'SYNCING', label: 'Syncing', position: 0, color: 'yellow' },
        { value: 'CONFIRMED', label: 'Confirmed', position: 1, color: 'green' },
        { value: 'CANCELLED', label: 'Cancelled', position: 2, color: 'gray' },
        { value: 'SYNC_FAILED', label: 'Sync failed', position: 3, color: 'red' },
      ],
    },
    {
      universalIdentifier: CONSULTATION_FIELD_IDS.scheduledStart,
      type: FieldType.DATE_TIME,
      name: 'scheduledStart',
      label: 'Scheduled Start',
      isNullable: true,
    },
    {
      universalIdentifier: CONSULTATION_FIELD_IDS.scheduledEnd,
      type: FieldType.DATE_TIME,
      name: 'scheduledEnd',
      label: 'Scheduled End',
      isNullable: true,
    },
    {
      universalIdentifier: CONSULTATION_FIELD_IDS.timezone,
      type: FieldType.TEXT,
      name: 'timezone',
      label: 'Timezone',
      defaultValue: 'America/Toronto',
      isNullable: false,
    },
    ...[
      [CONSULTATION_FIELD_IDS.contactName, 'contactName', 'Contact Name'],
      [CONSULTATION_FIELD_IDS.email, 'email', 'Email'],
      [CONSULTATION_FIELD_IDS.phone, 'phone', 'Phone'],
      [CONSULTATION_FIELD_IDS.notes, 'notes', 'Notes'],
      [CONSULTATION_FIELD_IDS.googleEventId, 'googleEventId', 'Google Event ID'],
      [CONSULTATION_FIELD_IDS.googleEventLink, 'googleEventLink', 'Google Event Link'],
      [CONSULTATION_FIELD_IDS.syncError, 'syncError', 'Sync Error'],
    ].map(([universalIdentifier, name, label]) => ({
      universalIdentifier,
      type: FieldType.TEXT as const,
      name,
      label,
      isNullable: true as const,
    })),
    {
      universalIdentifier: CONSULTATION_FIELD_IDS.mortgageLead,
      type: FieldType.RELATION,
      name: 'mortgageLead',
      label: 'Mortgage Lead',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: MORTGAGE_LEAD_OBJECT_ID,
      relationTargetFieldMetadataUniversalIdentifier: MORTGAGE_LEAD_FIELD_IDS.consultations,
      universalSettings: { relationType: RelationType.MANY_TO_ONE },
    },
    {
      universalIdentifier: CONSULTATION_FIELD_IDS.person,
      type: FieldType.RELATION,
      name: 'person',
      label: 'Person',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.person.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier:
        STANDARD_OBJECT_RELATION_FIELD_IDS.personConsultations,
      universalSettings: { relationType: RelationType.MANY_TO_ONE },
    },
  ],
});
