export const invoiceData = [
  {
    id: 1,
    company: 'Acme Corp',
    clientName: 'Maya Patel',
    dealValue: '$18,450',
    businessReport: 'Quarterly implementation and onboarding services',
    invoiceDate: 'Jan 12, 2026',
    status: 'Accepted',
    category: 'Implementation',
  },
  {
    id: 2,
    company: 'Northstar Labs',
    clientName: 'Ethan Brooks',
    dealValue: '$9,200',
    businessReport: 'Platform support renewal and reporting package',
    invoiceDate: 'Jan 18, 2026',
    status: 'Under Review',
    category: 'Subscription',
  },
  {
    id: 3,
    company: 'Harbor Studio',
    clientName: 'Sofia Garcia',
    dealValue: '$27,800',
    businessReport: 'Custom analytics dashboard delivery',
    invoiceDate: 'Jan 24, 2026',
    status: 'Processing',
    category: 'Consulting',
  },
  {
    id: 4,
    company: 'Vertex Systems',
    clientName: 'Noah Chen',
    dealValue: '$14,600',
    businessReport: 'Migration milestone and training invoice',
    invoiceDate: 'Feb 02, 2026',
    status: 'Rejected',
    category: 'Migration',
  },
  {
    id: 5,
    company: 'Cedar Finance',
    clientName: 'Ava Thompson',
    dealValue: '$33,120',
    businessReport: 'Enterprise workflow automation package',
    invoiceDate: 'Feb 08, 2026',
    status: 'Accepted',
    category: 'Automation',
  },
  {
    id: 6,
    company: 'Brightline Retail',
    clientName: 'Liam Wilson',
    dealValue: '$7,950',
    businessReport: 'Monthly commerce optimization services',
    invoiceDate: 'Feb 15, 2026',
    status: 'Processing',
    category: 'Optimization',
  },
  {
    id: 7,
    company: 'Summit Health',
    clientName: 'Olivia Morgan',
    dealValue: '$21,300',
    businessReport: 'Compliance reporting and audit support',
    invoiceDate: 'Feb 22, 2026',
    status: 'Under Review',
    category: 'Compliance',
  },
]
