/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    'fairlend-leads': FairlendLead;
    'fairlend-campaign-scans': FairlendCampaignScan;
    'fairlend-consultation-bookings': FairlendConsultationBooking;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'fairlend-leads': FairlendLeadsSelect<false> | FairlendLeadsSelect<true>;
    'fairlend-campaign-scans': FairlendCampaignScansSelect<false> | FairlendCampaignScansSelect<true>;
    'fairlend-consultation-bookings': FairlendConsultationBookingsSelect<false> | FairlendConsultationBookingsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'fairlend-consultation-settings': FairlendConsultationSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'fairlend-consultation-settings': FairlendConsultationSettingsSelect<false> | FairlendConsultationSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type:
      | 'none'
      | 'highImpact'
      | 'mediumImpact'
      | 'lowImpact'
      | 'watermelonHero1'
      | 'watermelonHeroSection1'
      | 'watermelonHeroSection2'
      | 'watermelonHeroSection3'
      | 'watermelonHeroSection4'
      | 'watermelonHeroSection5'
      | 'watermelonHeroSection6'
      | 'watermelonHeroSection7'
      | 'watermelonHeroSection8'
      | 'watermelonHeroSection9'
      | 'watermelonHeroSection10'
      | 'watermelonHeroSection11'
      | 'watermelonHeroSection12'
      | 'watermelonHeroSection13'
      | 'watermelonHeroSection14'
      | 'watermelonHeroSection15'
      | 'watermelonHeroSection16'
      | 'watermelonHeroSection17'
      | 'watermelonHeroSection18'
      | 'watermelonHeroSection19'
      | 'watermelonHeroSection20'
      | 'watermelonHeroSection21'
      | 'watermelonHeroSection22'
      | 'watermelonHeroSection23'
      | 'watermelonHeroSection24'
      | 'watermelonHeroSection25'
      | 'watermelonHeroSection26'
      | 'watermelonHeroSection27'
      | 'watermelonHeroSection28'
      | 'watermelonHeroSection29'
      | 'watermelonHeroSection30'
      | 'watermelonHeroSection31'
      | 'watermelonHeroSection32'
      | 'watermelonHeroSection33'
      | 'watermelonHeroSection34'
      | 'watermelonHeroSection35'
      | 'watermelonHeroSection36'
      | 'watermelonHeroSection37'
      | 'watermelonHeroSection38'
      | 'watermelonHeroSection39';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
    watermelonHero1?: {
      promptPlaceholder?: string | null;
      modeLabel?: string | null;
      depthLabel?: string | null;
      voiceLabel?: string | null;
      submitLabel?: string | null;
    };
    watermelonHeroSection?: {
      eyebrow?: string | null;
      brandLabel?: string | null;
      headline: string;
      accentText?: string | null;
      description?: string | null;
      primaryActionLabel?: string | null;
      primaryActionUrl?: string | null;
      secondaryActionLabel?: string | null;
      secondaryActionUrl?: string | null;
      backgroundMedia?: (number | null) | Media;
      foregroundMedia?: (number | null) | Media;
      logoMedia?: (number | null) | Media;
      navItems?:
        | {
            label: string;
            url?: string | null;
            id?: string | null;
          }[]
        | null;
      proofPoints?:
        | {
            value: string;
            label: string;
            id?: string | null;
          }[]
        | null;
      featureCards?:
        | {
            title: string;
            description?: string | null;
            media?: (number | null) | Media;
            id?: string | null;
          }[]
        | null;
    };
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | WatermelonBusinessManagementBlock
    | WatermelonBusinessOperationsDashboardBlock
    | WatermelonECommerceDashboardBlock
    | WatermelonErpDashboardBlock
    | WatermelonHrmBlock
    | WatermelonIncidentManagementBlock
    | WatermelonInvoiceGeneratorDashboardBlock
    | WatermelonInvoiceManagerDashboardBlock
    | WatermelonIssueTrackingBlock
    | WatermelonLeadDashboardBlock
    | WatermelonMailDashboardBlock
    | WatermelonMeetingsDashboardBlock
    | WatermelonPaymentOperationsDashboardBlock
    | WatermelonProjectManagementDashboardBlock
    | WatermelonSalesDashboardBlock
    | WatermelonTaskManagementDashboardBlock
    | WatermelonWorkflowManagementDashboardBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonBusinessManagementBlock".
 */
export interface WatermelonBusinessManagementBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonBusinessManagement';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonBusinessOperationsDashboardBlock".
 */
export interface WatermelonBusinessOperationsDashboardBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonBusinessOperationsDashboard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonECommerceDashboardBlock".
 */
export interface WatermelonECommerceDashboardBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonECommerceDashboard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonErpDashboardBlock".
 */
export interface WatermelonErpDashboardBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonErpDashboard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonHrmBlock".
 */
export interface WatermelonHrmBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonHrm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonIncidentManagementBlock".
 */
export interface WatermelonIncidentManagementBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonIncidentManagement';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonInvoiceGeneratorDashboardBlock".
 */
export interface WatermelonInvoiceGeneratorDashboardBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonInvoiceGeneratorDashboard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonInvoiceManagerDashboardBlock".
 */
export interface WatermelonInvoiceManagerDashboardBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonInvoiceManagerDashboard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonIssueTrackingBlock".
 */
export interface WatermelonIssueTrackingBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonIssueTracking';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonLeadDashboardBlock".
 */
export interface WatermelonLeadDashboardBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonLeadDashboard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonMailDashboardBlock".
 */
export interface WatermelonMailDashboardBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonMailDashboard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonMeetingsDashboardBlock".
 */
export interface WatermelonMeetingsDashboardBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonMeetingsDashboard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonPaymentOperationsDashboardBlock".
 */
export interface WatermelonPaymentOperationsDashboardBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonPaymentOperationsDashboard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonProjectManagementDashboardBlock".
 */
export interface WatermelonProjectManagementDashboardBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonProjectManagementDashboard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonSalesDashboardBlock".
 */
export interface WatermelonSalesDashboardBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonSalesDashboard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonTaskManagementDashboardBlock".
 */
export interface WatermelonTaskManagementDashboardBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonTaskManagementDashboard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonWorkflowManagementDashboardBlock".
 */
export interface WatermelonWorkflowManagementDashboardBlock {
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  theme?: ('light' | 'dark' | 'muted') | null;
  primaryActionLabel?: string | null;
  primaryActionUrl?: string | null;
  secondaryActionLabel?: string | null;
  secondaryActionUrl?: string | null;
  media?: (number | null) | Media;
  secondaryMedia?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        description?: string | null;
        badge?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'watermelonWorkflowManagementDashboard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fairlend-leads".
 */
export interface FairlendLead {
  id: number;
  /**
   * Stable UUID shared by the public homepage form and intake wizard.
   */
  leadId: string;
  status: 'draft' | 'started' | 'submitted';
  /**
   * Editable admin pipeline stage for follow-up.
   */
  workflowStatus:
    | 'new'
    | 'contact_attempted'
    | 'contacted'
    | 'qualified'
    | 'consultation_booked'
    | 'working_file'
    | 'closed_won'
    | 'closed_lost';
  priority: 'high' | 'normal' | 'low';
  /**
   * Optional follow-up date/time for the admin workflow.
   */
  nextActionAt?: string | null;
  intent?: string | null;
  source: string;
  /**
   * QR campaign that first attributed this lead, when available.
   */
  campaign?: string | null;
  /**
   * QR scan id linked to this lead, when available.
   */
  campaignScanId?: string | null;
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  formattedAddress?: string | null;
  /**
   * Google Places ID captured from autocomplete when available.
   */
  placeId?: string | null;
  /**
   * Full intake wizard payload.
   */
  intake?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  intakeType?: string | null;
  intakeAmount?: string | null;
  intakeTimeline?: string | null;
  intakeProjectStage?: string | null;
  intakeFinancingNeeds?: string | null;
  intakePropertyValue?: string | null;
  intakeMortgageBalance?: string | null;
  intakeAdditionalLiens?: string | null;
  intakeInvestmentFocus?: string | null;
  /**
   * Compact one-line summary of the submitted intake details.
   */
  intakeSummary?: string | null;
  /**
   * Submitted notes, context, message, or document status.
   */
  intakeDetail?: string | null;
  /**
   * Full Google address-details payload, when available.
   */
  addressDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Campaign attribution payload captured from QR redirects.
   */
  attribution?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Internal notes for admin follow-up. Not shown to visitors.
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fairlend-campaign-scans".
 */
export interface FairlendCampaignScan {
  id: number;
  /**
   * Stable UUID for this QR scan event.
   */
  scanId: string;
  campaign: string;
  source: string;
  destination: string;
  /**
   * Lead id attached when this scan becomes a submitted lead.
   */
  convertedLeadId?: string | null;
  convertedAt?: string | null;
  capturedAt: string;
  referrer?: string | null;
  userAgent?: string | null;
  /**
   * SHA-256 hash of the client IP. Raw IP addresses are not stored.
   */
  hashedIp?: string | null;
  queryParams?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fairlend-consultation-bookings".
 */
export interface FairlendConsultationBooking {
  id: number;
  bookingId: string;
  status: 'syncing' | 'confirmed' | 'cancelled' | 'sync_failed';
  scheduledStart: string;
  scheduledEnd: string;
  timezone: string;
  name: string;
  email: string;
  phone?: string | null;
  notes?: string | null;
  source: string;
  googleEventId?: string | null;
  /**
   * Google Calendar event URL returned after sync.
   */
  googleEventLink?: string | null;
  syncError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'fairlend-leads';
        value: number | FairlendLead;
      } | null)
    | ({
        relationTo: 'fairlend-campaign-scans';
        value: number | FairlendCampaignScan;
      } | null)
    | ({
        relationTo: 'fairlend-consultation-bookings';
        value: number | FairlendConsultationBooking;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
        watermelonHero1?:
          | T
          | {
              promptPlaceholder?: T;
              modeLabel?: T;
              depthLabel?: T;
              voiceLabel?: T;
              submitLabel?: T;
            };
        watermelonHeroSection?:
          | T
          | {
              eyebrow?: T;
              brandLabel?: T;
              headline?: T;
              accentText?: T;
              description?: T;
              primaryActionLabel?: T;
              primaryActionUrl?: T;
              secondaryActionLabel?: T;
              secondaryActionUrl?: T;
              backgroundMedia?: T;
              foregroundMedia?: T;
              logoMedia?: T;
              navItems?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              proofPoints?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              featureCards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    media?: T;
                    id?: T;
                  };
            };
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        watermelonBusinessManagement?: T | WatermelonBusinessManagementBlockSelect<T>;
        watermelonBusinessOperationsDashboard?: T | WatermelonBusinessOperationsDashboardBlockSelect<T>;
        watermelonECommerceDashboard?: T | WatermelonECommerceDashboardBlockSelect<T>;
        watermelonErpDashboard?: T | WatermelonErpDashboardBlockSelect<T>;
        watermelonHrm?: T | WatermelonHrmBlockSelect<T>;
        watermelonIncidentManagement?: T | WatermelonIncidentManagementBlockSelect<T>;
        watermelonInvoiceGeneratorDashboard?: T | WatermelonInvoiceGeneratorDashboardBlockSelect<T>;
        watermelonInvoiceManagerDashboard?: T | WatermelonInvoiceManagerDashboardBlockSelect<T>;
        watermelonIssueTracking?: T | WatermelonIssueTrackingBlockSelect<T>;
        watermelonLeadDashboard?: T | WatermelonLeadDashboardBlockSelect<T>;
        watermelonMailDashboard?: T | WatermelonMailDashboardBlockSelect<T>;
        watermelonMeetingsDashboard?: T | WatermelonMeetingsDashboardBlockSelect<T>;
        watermelonPaymentOperationsDashboard?: T | WatermelonPaymentOperationsDashboardBlockSelect<T>;
        watermelonProjectManagementDashboard?: T | WatermelonProjectManagementDashboardBlockSelect<T>;
        watermelonSalesDashboard?: T | WatermelonSalesDashboardBlockSelect<T>;
        watermelonTaskManagementDashboard?: T | WatermelonTaskManagementDashboardBlockSelect<T>;
        watermelonWorkflowManagementDashboard?: T | WatermelonWorkflowManagementDashboardBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonBusinessManagementBlock_select".
 */
export interface WatermelonBusinessManagementBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonBusinessOperationsDashboardBlock_select".
 */
export interface WatermelonBusinessOperationsDashboardBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonECommerceDashboardBlock_select".
 */
export interface WatermelonECommerceDashboardBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonErpDashboardBlock_select".
 */
export interface WatermelonErpDashboardBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonHrmBlock_select".
 */
export interface WatermelonHrmBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonIncidentManagementBlock_select".
 */
export interface WatermelonIncidentManagementBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonInvoiceGeneratorDashboardBlock_select".
 */
export interface WatermelonInvoiceGeneratorDashboardBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonInvoiceManagerDashboardBlock_select".
 */
export interface WatermelonInvoiceManagerDashboardBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonIssueTrackingBlock_select".
 */
export interface WatermelonIssueTrackingBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonLeadDashboardBlock_select".
 */
export interface WatermelonLeadDashboardBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonMailDashboardBlock_select".
 */
export interface WatermelonMailDashboardBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonMeetingsDashboardBlock_select".
 */
export interface WatermelonMeetingsDashboardBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonPaymentOperationsDashboardBlock_select".
 */
export interface WatermelonPaymentOperationsDashboardBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonProjectManagementDashboardBlock_select".
 */
export interface WatermelonProjectManagementDashboardBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonSalesDashboardBlock_select".
 */
export interface WatermelonSalesDashboardBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonTaskManagementDashboardBlock_select".
 */
export interface WatermelonTaskManagementDashboardBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WatermelonWorkflowManagementDashboardBlock_select".
 */
export interface WatermelonWorkflowManagementDashboardBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  theme?: T;
  primaryActionLabel?: T;
  primaryActionUrl?: T;
  secondaryActionLabel?: T;
  secondaryActionUrl?: T;
  media?: T;
  secondaryMedia?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fairlend-leads_select".
 */
export interface FairlendLeadsSelect<T extends boolean = true> {
  leadId?: T;
  status?: T;
  workflowStatus?: T;
  priority?: T;
  nextActionAt?: T;
  intent?: T;
  source?: T;
  campaign?: T;
  campaignScanId?: T;
  name?: T;
  email?: T;
  phone?: T;
  address?: T;
  formattedAddress?: T;
  placeId?: T;
  intake?: T;
  intakeType?: T;
  intakeAmount?: T;
  intakeTimeline?: T;
  intakeProjectStage?: T;
  intakeFinancingNeeds?: T;
  intakePropertyValue?: T;
  intakeMortgageBalance?: T;
  intakeAdditionalLiens?: T;
  intakeInvestmentFocus?: T;
  intakeSummary?: T;
  intakeDetail?: T;
  addressDetails?: T;
  attribution?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fairlend-campaign-scans_select".
 */
export interface FairlendCampaignScansSelect<T extends boolean = true> {
  scanId?: T;
  campaign?: T;
  source?: T;
  destination?: T;
  convertedLeadId?: T;
  convertedAt?: T;
  capturedAt?: T;
  referrer?: T;
  userAgent?: T;
  hashedIp?: T;
  queryParams?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fairlend-consultation-bookings_select".
 */
export interface FairlendConsultationBookingsSelect<T extends boolean = true> {
  bookingId?: T;
  status?: T;
  scheduledStart?: T;
  scheduledEnd?: T;
  timezone?: T;
  name?: T;
  email?: T;
  phone?: T;
  notes?: T;
  source?: T;
  googleEventId?: T;
  googleEventLink?: T;
  syncError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fairlend-consultation-settings".
 */
export interface FairlendConsultationSetting {
  id: number;
  /**
   * IANA timezone used to interpret all schedule rules.
   */
  timezone: string;
  /**
   * Length of each consultation slot.
   */
  slotDurationMinutes: number;
  /**
   * Blocked recovery time after each slot.
   */
  bufferMinutes: number;
  /**
   * How far ahead visitors must book.
   */
  minimumNoticeHours: number;
  /**
   * Maximum number of days visitors can book into the future.
   */
  bookingWindowDays: number;
  /**
   * Array of weekday rules: { "weekday": "monday", "enabled": true, "startTime": "09:00", "endTime": "17:00" }.
   */
  weeklyAvailability:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of blackout rules: { "date": "2026-07-20", "allDay": true } or with startTime/endTime for partial blocks.
   */
  blackoutDates:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of one-off openings: { "date": "2026-07-25", "enabled": true, "startTime": "10:00", "endTime": "14:00" }.
   */
  extraAvailability:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fairlend-consultation-settings_select".
 */
export interface FairlendConsultationSettingsSelect<T extends boolean = true> {
  timezone?: T;
  slotDurationMinutes?: T;
  bufferMinutes?: T;
  minimumNoticeHours?: T;
  bookingWindowDays?: T;
  weeklyAvailability?: T;
  blackoutDates?: T;
  extraAvailability?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}